package com.aryntra.pravah.security.authentication;

import java.security.SecureRandom;
import java.time.Instant;
import java.util.Arrays;
import java.util.Objects;
import java.util.UUID;

/**
 * A cryptographically secure, fresh, and unpredictable challenge generated by a verifier.
 *
 * <p>Maintains strict replay resistance through single-use consumption tracking and
 * an epoch-based validity window.</p>
 *
 * <p>SX.3 — Authentication Handshake & Proof of Possession</p>
 */
public final class AuthenticationChallenge {
    private static final SecureRandom SECURE_RANDOM = new SecureRandom();
    private static final int CHALLENGE_BYTES_SIZE = 32; // Cryptographically strong 256-bit entropy
    private static final long DEFAULT_VALIDITY_DURATION_MS = 60_000; // 60 seconds of valid window

    private final String challengeId;
    private final byte[] challengeBytes;
    private final Instant expiryTime;
    private volatile boolean consumed = false;

    private AuthenticationChallenge(String challengeId, byte[] challengeBytes, Instant expiryTime) {
        this.challengeId = Objects.requireNonNull(challengeId, "challengeId must not be null");
        this.challengeBytes = Objects.requireNonNull(challengeBytes, "challengeBytes must not be null").clone();
        this.expiryTime = Objects.requireNonNull(expiryTime, "expiryTime must not be null");
    }

    /**
     * Generates a fresh, unpredictable challenge with standard entropy and validity period.
     *
     * @return a new {@link AuthenticationChallenge} instance
     */
    public static AuthenticationChallenge generate() {
        byte[] bytes = new byte[CHALLENGE_BYTES_SIZE];
        SECURE_RANDOM.nextBytes(bytes);
        String id = UUID.randomUUID().toString();
        Instant expiry = Instant.now().plusMillis(DEFAULT_VALIDITY_DURATION_MS);
        return new AuthenticationChallenge(id, bytes, expiry);
    }

    /**
     * Factory method for restoring or custom creation (primarily for testing or cross-network deserialization).
     */
    public static AuthenticationChallenge of(String challengeId, byte[] challengeBytes, Instant expiryTime) {
        return new AuthenticationChallenge(challengeId, challengeBytes, expiryTime);
    }

    /** Unique challenge sequence identifier. */
    public String challengeId() {
        return challengeId;
    }

    /**
     * Defensive copy of the raw cryptographically secure challenge bytes.
     */
    public byte[] challengeBytes() {
        return challengeBytes.clone();
    }

    /** The expiration timestamp for this challenge. */
    public Instant expiryTime() {
        return expiryTime;
    }

    /**
     * Checks if this challenge has expired based on system clock.
     */
    public boolean isExpired() {
        return Instant.now().isAfter(expiryTime);
    }

    /**
     * Checks if the challenge has already been consumed.
     */
    public boolean isConsumed() {
        return consumed;
    }

    /**
     * Marks the challenge as consumed. This operation is thread-safe and irreversible.
     *
     * @return {@code true} if successfully marked consumed; {@code false} if it was already consumed
     */
    public synchronized boolean consume() {
        if (consumed) {
            return false;
        }
        consumed = true;
        return true;
    }

    /**
     * Verifies if this specific challenge is valid for validation right now.
     * Checks both expiry and consumption states.
     */
    public boolean isValid() {
        return !consumed && !isExpired();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        AuthenticationChallenge that = (AuthenticationChallenge) o;
        return challengeId.equals(that.challengeId)
                && Arrays.equals(challengeBytes, that.challengeBytes)
                && expiryTime.equals(that.expiryTime);
    }

    @Override
    public int hashCode() {
        int result = Objects.hash(challengeId, expiryTime);
        result = 31 * result + Arrays.hashCode(challengeBytes);
        return result;
    }

    @Override
    public String toString() {
        return "AuthenticationChallenge[id=" + challengeId
                + ", size=" + challengeBytes.length
                + ", isValid=" + isValid()
                + "]";
    }
}