package com.aryntra.pravah.security.authentication;

/**
 * Represents the final outcome of a Cryptographic Proof of Possession verification.
 *
 * <p>Authentication is fail-closed. Successful verification returns {@link #SUCCESS},
 * while failures are classified with rich reasons to aid system diagnostics without
 * exposing raw cryptographic exceptions to the caller.</p>
 *
 * <p>SX.3 — Authentication Handshake & Proof of Possession</p>
 */
public enum AuthenticationResult {
    /** The digital signature is valid, and the challenge was successfully proved. */
    SUCCESS,

    /** The presented proof had an incorrect signature or failed cryptographic verification. */
    INVALID_PROOF,

    /** The challenge has expired, was already consumed, or was not generated by this verifier. */
    CHALLENGE_EXPIRED_OR_CONSUMED,

    /** The claimed identity is missing or does not match the public key in the proof. */
    IDENTITY_MISMATCH,

    /** The signature, public key, or context structure was malformed or corrupted. */
    MALFORMED_INPUT,

    /** The cryptographic algorithm used in the identity is unsupported. */
    UNSUPPORTED_ALGORITHM;

    /**
     * Helper to check if the result represents a successful authentication.
     *
     * @return {@code true} if successful; {@code false} if any failure occurred
     */
    public boolean isSuccess() {
        return this == SUCCESS;
    }
}